# Generated by Django 4.2.7 on 2023-12-11 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('offered_price', models.IntegerField(blank=True, null=True)),
                ('engine', models.CharField(default='', max_length=50)),
                ('images_list', models.TextField(default='[]')),
                ('is_used', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=1900)),
                ('is_all_options', models.BooleanField(default=False)),
                ('options_list', models.TextField(default='[]')),
                ('mileage', models.IntegerField()),
                ('phone_numbers', models.TextField(default='[]')),
                ('city', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('likes_count', models.IntegerField(default=0)),
                ('dislikes_count', models.IntegerField(default=0)),
                ('main_image', models.TextField(default='')),
                ('views', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=50)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
