# Generated by Django 4.2.7 on 2023-12-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
