# Generated by Django 4.2.7 on 2023-12-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_color_country_document_fuel_gearbox_option_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articels', to='article.brand'),
        ),
        migrations.AddField(
            model_name='article',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.color'),
        ),
        migrations.AddField(
            model_name='article',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.document'),
        ),
        migrations.AddField(
            model_name='article',
            name='fuel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.fuel'),
        ),
        migrations.AddField(
            model_name='article',
            name='gear_box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.gearbox'),
        ),
        migrations.AddField(
            model_name='article',
            name='options',
            field=models.ManyToManyField(to='article.option'),
        ),
        migrations.AddField(
            model_name='article',
            name='other_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
