# Generated by Django 4.2.7 on 2023-12-29 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0007_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dislikers',
            field=models.ManyToManyField(related_name='disliked_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='likers',
            field=models.ManyToManyField(related_name='liked_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
