# Generated by Django 4.2.7 on 2024-01-07 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0009_alter_article_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='savers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
