# Generated by Django 4.2.7 on 2024-01-24 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0012_remove_article_savers_savedarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedarticle',
            name='saver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
