# Generated by Django 4.2.7 on 2024-02-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_article_scoore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='scoore',
            new_name='popularity_scoore',
        ),
    ]
