# Generated by Django 4.2.7 on 2024-02-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_rename_scoore_article_popularity_scoore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='popularity_scoore',
            new_name='scoore',
        ),
    ]
