# Generated by Django 4.2.7 on 2024-02-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_rename_popularity_scoore_article_scoore'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_per',
            field=models.FloatField(default=0),
        ),
    ]
