# Generated by Django 4.2.7 on 2024-02-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_article_like_per'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='scoore',
            field=models.FloatField(default=0),
        ),
    ]
