# Generated by Django 4.2.7 on 2024-02-11 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0022_articlesuggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='images_list',
        ),
    ]
