# Generated by Django 4.2.7 on 2024-02-11 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_remove_article_images_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='main_image',
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
                ('path', models.TextField(default='')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
            ],
        ),
    ]
