# Generated by Django 4.2.7 on 2024-02-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_mainimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='article.article'),
        ),
    ]
