# Generated by Django 4.2.7 on 2024-02-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0026_alter_mainimage_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
    ]
