# Generated by Django 4.2.7 on 2024-02-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0031_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(related_name='brands', to='article.category'),
        ),
    ]
