# Generated by Django 4.2.7 on 2024-02-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0033_alter_brand_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='brands', to='article.category'),
        ),
    ]
