# Generated by Django 4.2.7 on 2024-02-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0035_alter_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='other_brand',
            field=models.CharField(default='', max_length=50),
        ),
    ]
