# Generated by Django 4.2.7 on 2024-03-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0040_brand_name_ar_brand_name_en_brand_name_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
