# Generated by Django 4.2.7 on 2024-03-06 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0042_remove_option_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='country',
            name='slug',
        ),
    ]
