# Generated by Django 4.2.7 on 2024-03-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0043_remove_brand_slug_remove_country_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
