# Generated by Django 4.2.7 on 2024-03-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0044_remove_brand_country_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.TextField(default=''),
        ),
    ]
