# Generated by Django 4.2.7 on 2024-04-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0045_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainimage',
            name='article',
        ),
        migrations.RemoveField(
            model_name='mainimage',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='images_list',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='MainImage',
        ),
    ]
