# Generated by Django 4.2.7 on 2024-01-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_rename_is_seen_message_is_seen_by_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
