# Generated by Django 4.2.7 on 2024-01-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_conversation_is_acknowledged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message__sent_at']},
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
    ]
