# Generated by Django 4.2.7 on 2024-01-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='is_acknowledged',
            new_name='acknowledged',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_seen_by_receiver',
            new_name='seen_by_receiver',
        ),
    ]
