# Generated by Django 4.2.7 on 2023-12-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_bio_alter_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_150_url',
            field=models.TextField(default='/media/others/user_150.png'),
        ),
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.TextField(default='/media/others/user.png'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_150',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
