# Generated by Django 4.2.7 on 2023-12-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_image_150_url_profile_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_150_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(default='/media/others/user.png'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_150',
            field=models.TextField(default='/media/others/user_150.png'),
        ),
    ]
