# Generated by Django 4.2.7 on 2023-12-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_image_150_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(default='/static/others/user.png'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_150',
            field=models.TextField(default='/static/others/user_150.png'),
        ),
    ]
