# Generated by Django 4.2.7 on 2023-12-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_profile_image_alter_profile_image_150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_update_count',
            field=models.IntegerField(default=0),
        ),
    ]
