# Generated by Django 4.2.7 on 2024-02-09 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
    ]
