# Generated by Django 4.2.7 on 2024-02-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_delete_user2'),
    ]

    operations = [
    ]
