# Generated by Django 4.2.7 on 2024-02-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20240209_1101'),
    ]

    operations = [
    ]
