# Generated by Django 4.2.7 on 2024-02-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20240209_1104'),
    ]

    operations = [
    ]
