# Generated by Django 4.2.7 on 2024-02-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_userreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
