# Generated by Django 4.2.7 on 2024-02-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_review_delete_userreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
