# Generated by Django 4.2.7 on 2024-02-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_remove_profile_credibility_remove_profile_scoore'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
    ]
