# Generated by Django 4.2.7 on 2024-02-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_profile_birth_day_profile_is_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_day_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_public',
            field=models.BooleanField(default=False),
        ),
    ]
