# Generated by Django 4.2.7 on 2024-02-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_profile_birth_day_public_profile_email_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_day_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location_public',
            field=models.BooleanField(default=True),
        ),
    ]
