# Generated by Django 4.2.7 on 2024-02-17 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_profile_facebok_profile_instagram_profile_is_page_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebok',
            new_name='facebook',
        ),
    ]
