# Generated by Django 4.2.7 on 2024-02-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_company_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='page_website',
            new_name='website',
        ),
    ]
