# Generated by Django 4.2.7 on 2024-02-18 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0039_page_delete_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_public',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_150',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_update_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_page',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location_public',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='other_socials',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tiktok',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='youtube',
        ),
        migrations.CreateModel(
            name='UserExtention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_public', models.BooleanField(default=True)),
                ('image', models.TextField(default='/static/others/user.png')),
                ('image_150', models.TextField(default='/static/others/user_150.png')),
                ('bio', models.TextField(default='', max_length=255)),
                ('image_update_count', models.IntegerField(default=1)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_public', models.BooleanField(default=True)),
                ('is_page', models.BooleanField(default=False)),
                ('facebook', models.TextField(blank=True, max_length=255, null=True)),
                ('instagram', models.TextField(blank=True, max_length=255, null=True)),
                ('tiktok', models.TextField(blank=True, max_length=255, null=True)),
                ('youtube', models.TextField(blank=True, max_length=255, null=True)),
                ('twitter', models.TextField(blank=True, max_length=255, null=True)),
                ('linkedin', models.TextField(blank=True, max_length=255, null=True)),
                ('other_socials', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
