# Generated by Django 4.2.7 on 2024-02-18 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0040_remove_profile_bio_remove_profile_email_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextention',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extention', to=settings.AUTH_USER_MODEL),
        ),
    ]
