# Generated by Django 4.2.7 on 2024-02-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='location',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='page',
            name='website',
            field=models.TextField(default='', max_length=255),
        ),
    ]
