# Generated by Django 4.2.7 on 2024-02-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_alter_page_location_alter_page_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextention',
            name='facebook',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='instagram',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='linkedin',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='other_socials',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='tiktok',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='twitter',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='youtube',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
