# Generated by Django 4.2.7 on 2024-02-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_alter_profile_birth_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextention',
            name='facebook',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='instagram',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='linkedin',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='other_socials',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='tiktok',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='twitter',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userextention',
            name='youtube',
            field=models.TextField(default='', max_length=255),
        ),
    ]
