# Generated by Django 4.2.7 on 2024-02-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_alter_profile_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
