# Generated by Django 4.2.7 on 2024-03-01 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0016_rename_swiperad_ad'),
        ('user', '0049_remove_profile_city_remove_profile_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextention',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userextention',
            name='state',
        ),
        migrations.AddField(
            model_name='page',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='page',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.state'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.state'),
        ),
    ]
