# Generated by Django 4.2.7 on 2024-03-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_remove_userextention_city_remove_userextention_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='location',
        ),
        migrations.AddField(
            model_name='page',
            name='street',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.TextField(default='', max_length=255),
        ),
    ]
