# Generated by Django 4.2.7 on 2024-03-02 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0016_rename_swiperad_ad'),
        ('user', '0051_remove_page_location_page_street_profile_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='city',
        ),
        migrations.RemoveField(
            model_name='page',
            name='state',
        ),
        migrations.RemoveField(
            model_name='page',
            name='street',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=50)),
                ('street', models.TextField(default='', max_length=255)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.state')),
            ],
        ),
    ]
