# Generated by Django 4.2.7 on 2024-03-02 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_remove_page_city_remove_page_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.location'),
        ),
    ]
