# Generated by Django 4.2.7 on 2024-03-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0016_rename_swiperad_ad'),
        ('user', '0054_remove_page_location_remove_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='others.state'),
        ),
    ]
