# Generated by Django 4.2.7 on 2024-03-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_alter_location_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextention',
            name='location_public',
        ),
        migrations.AddField(
            model_name='location',
            name='location_public',
            field=models.BooleanField(default=True),
        ),
    ]
