# Generated by Django 4.2.7 on 2024-03-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_remove_userextention_location_public_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='street',
            new_name='address',
        ),
    ]
