# Generated by Django 4.2.7 on 2024-03-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0061_usertoken_fcmtoken_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcmtoken',
            old_name='last_active',
            new_name='created_at',
        ),
    ]
