# Generated by Django 4.2.7 on 2024-03-10 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0062_rename_last_active_fcmtoken_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='FCMToken',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
