# Generated by Django 4.2.7 on 2024-03-12 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0065_alter_fcmtoken_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmtoken',
            name='user_token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_token', to='user.usertoken'),
        ),
    ]
