# Generated by Django 4.2.7 on 2024-03-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0066_alter_fcmtoken_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcmtoken',
            old_name='last_active',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='usertoken',
            name='created_at',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
