# Generated by Django 4.2.7 on 2024-03-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0067_rename_last_active_fcmtoken_last_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccountUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
            ],
        ),
    ]
