# Generated by Django 4.2.7 on 2024-03-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_deletedaccountusername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedAccountUsername',
        ),
    ]
