# Generated by Django 4.2.7 on 2024-03-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_delete_deletedaccountusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccountUsername',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
