# Generated by Django 4.2.7 on 2024-03-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_userpassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeletedAccountUsername',
            new_name='DeletedAccount',
        ),
    ]
