# Generated by Django 4.2.7 on 2024-03-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_rename_deletedaccountusername_deletedaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedaccount',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
