# Generated by Django 4.2.7 on 2024-04-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_deletedaccount_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextention',
            name='rank',
        ),
    ]
