# Generated by Django 4.2.7 on 2024-05-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0078_alter_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path_150',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='image',
            name='url_150',
            field=models.TextField(default=''),
        ),
    ]
