# Generated by Django 4.2.7 on 2024-05-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0079_image_path_150_image_url_150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextention',
            name='image_update_count',
        ),
    ]
