# Generated by Django 4.2.7 on 2024-01-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('comment', 'Comment'), ('message', 'Message'), ('follow', 'Follow'), ('leader_posted', 'LeaderPosted')], max_length=20),
        ),
    ]
