# Generated by Django 4.2.7 on 2024-01-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_notification_notified_alter_notification_notifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
