# Generated by Django 4.2.7 on 2024-01-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0006_alter_notification_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_acknowledged',
            new_name='acknowledged',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='is_seen',
            new_name='seen',
        ),
    ]
