# Generated by Django 4.2.7 on 2024-01-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0007_rename_is_acknowledged_notification_acknowledged_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='acknowledged',
            new_name='is_acknowledged',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='seen',
            new_name='is_seen',
        ),
    ]
