# Generated by Django 4.2.7 on 2024-02-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0010_report_reporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='note',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
