# Generated by Django 4.2.7 on 2024-02-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0011_report_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='User',
            new_name='user',
        ),
    ]
