# Generated by Django 4.2.7 on 2024-02-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0012_rename_user_report_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='text',
        ),
    ]
