# Generated by Django 4.2.7 on 2024-02-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0013_remove_notification_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('comment', 'Comment'), ('follow', 'Follow'), ('leader_posted', 'LeaderPosted')], max_length=20),
        ),
    ]
