# Generated by Django 4.2.7 on 2024-03-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0014_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiperAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('swiper', 'Swiper'), ('static', 'Static')], max_length=20)),
                ('order', models.IntegerField()),
                ('url', models.TextField()),
                ('image', models.ImageField(upload_to='swpiper_ad_images/')),
            ],
        ),
    ]
