# Generated by Django 4.2.7 on 2024-03-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0015_swiperad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SwiperAd',
            new_name='Ad',
        ),
    ]
