# Generated by Django 4.2.7 on 2024-03-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0016_rename_swiperad_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='name_ar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='name_fr',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
