# Generated by Django 4.2.7 on 2024-03-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0017_state_name_ar_state_name_en_state_name_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='slug',
        ),
    ]
