# Generated by Django 4.2.7 on 2024-03-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0020_alter_report_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('comment', 'Comment'), ('follow', 'Follow'), ('leader_posted', 'LeaderPosted'), ('admin_reply', 'AdminReply')], max_length=20),
        ),
    ]
