# Generated by Django 4.2.7 on 2024-03-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0022_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
    ]
