# Generated by Django 4.2.7 on 2024-03-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0023_notificationtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtext',
            name='text_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtext',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationtext',
            name='text_fr',
            field=models.TextField(null=True),
        ),
    ]
