# Generated by Django 4.2.7 on 2024-03-24 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0024_notificationtext_text_ar_notificationtext_text_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationText',
        ),
    ]
