# Generated by Django 4.2.7 on 2024-03-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0026_notification_extra_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='extra_text',
            new_name='text',
        ),
    ]
