# Generated by Django 4.2.7 on 2024-03-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0028_contactus_acknoleged_report_acknoleged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
