# Generated by Django 4.2.7 on 2024-03-27 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0029_alter_report_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_at']},
        ),
    ]
