# Generated by Django 4.2.7 on 2024-03-27 23:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('others', '0032_alter_contactus_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='note',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter',
        ),
        migrations.AddField(
            model_name='report',
            name='reporters',
            field=models.ManyToManyField(related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
