# Generated by Django 4.2.7 on 2024-03-28 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0045_comment_slug'),
        ('others', '0034_alter_report_options_remove_report_acknoleged_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-last_unacknoleged']},
        ),
        migrations.AddField(
            model_name='report',
            name='acknoleged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='article.article'),
        ),
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='article.comment'),
        ),
        migrations.AddField(
            model_name='report',
            name='last_unacknoleged',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ruled_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to=settings.AUTH_USER_MODEL),
        ),
    ]
