# Generated by Django 4.2.7 on 2024-03-28 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0035_alter_report_options_report_acknoleged_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='last_unacknoleged',
            new_name='created_at',
        ),
    ]
